name: "📚 Blog Updater"

on:
  workflow_dispatch:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs Every Day

jobs:
  update-readme-with-blogs:
    name: "Update this repo's README with latest blog posts"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@v2

      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@main"
      # - uses: gautamkrishnar/blog-post-workflow@master
        with:
          USERNAME: 'victor'
          COUNT: 5
          STYLE: "blog-left"
          BLOG_URL: 'https://vickyikechukwu.hashnode.dev/'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
