name: "📚 Blog Updater"

on:
  workflow_dispatch:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
    workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blogs:
    name: "Update Blogs "
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@v2

      - name: "📚  Hashnode Updater"
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://vickyikechukwu.hashnode.dev/rss.xml"
          USERNAME: 'VickyIkechukwu'
          COUNT: 5
          STYLE: "blog-left"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
