name: "📚 Blog Updater"

on:
  workflow_dispatch:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour

jobs:
  update-readme-with-blogs:
    name: "Update Blogs "
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@main"
        with:
          USERNAME: 'VickyIkechukwu'
          COUNT: 5
          STYLE: "blog-left"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
